#!/usr/bin/perl
use warnings;
use strict;
use Getopt::Long;
use FindBin qw($Bin);
use lib "$FindBin::Bin/../source";
use CF::Constants;
use CF::Helpers;
use File::Copy;

# Get Options
my $required_cores;
my $required_mem = '';
my $result = GetOptions ("cores=i" => \$required_cores, "mem" => \$required_mem);

# QSUB SETUP
# --cores i = offered cores. Return number of required cores.
if($required_cores){
	print 1;
	exit;
}
# --mem. Return the required memory allocation.
if($required_mem){
	print '1G';
	exit;
}

# MODULE
# Read in the input files from the run file
my ($files, $runfile, $job_id, $prev_job_id, $cores, $mem, $parameters, $config_ref) = CF::Helpers::load_runfile_params(@ARGV);

# Strip off all of the bismark stuff from the input filename
my $dir = ${$files}[0];
$dir =~ s/.gz$//;
$dir =~ s/.txt$//; 
$dir =~ s/.deduplicated$//;
$dir =~ s/_bt2$//;
$dir =~ s/_bismark$//;
$dir =~ s/.gz$//;
$dir =~ s/.fq$//;
$dir =~ s/_val_[12]$//;
$dir =~ s/_trimmed$//;
$dir =~ s/_[12]$//;
$dir =~ s/^(CpG|Non_CpG|CHG|CHH)_//;
$dir =~ s/^[COBT]+_//; 


# make directory
mkdir $dir;

# move matching files into this directory
foreach my $file (glob('*')) {
	if($file =~ /$dir/){
		move ($file, $dir."/".$file);
	}
}

# run bismark2report in directory
chdir ($dir);
system ("bismark2report");
chdir ("../");
