#!/usr/bin/perl
use warnings;
use strict;
use Getopt::Long;
use FindBin qw($Bin);
use lib "$FindBin::Bin/../source";
use CF::Constants;
use CF::Helpers;
use POSIX;

# MODULE

my $timestart = time;

# Read in the input files from the run file
my ($runfile, $job_id, $url, $dl_fn) = @ARGV;

warn "\n---------------------\nDownloading $dl_fn from $url\nStarted at ".strftime("%H:%M, %A - %d/%m/%Y", localtime)."\n";

open (RUN,'>>',$runfile) or die "Can't write to $runfile: $!";

if(!system ("wget -nv --tries=10 --output-document=$dl_fn $url")){
	# Download worked - print resulting filename to results file
	print RUN "$job_id\t$dl_fn\n";
	warn "###CF Downloading $dl_fn succeeded\n";
} else {
	# Download failed - don't print a filename so that child processes exit silently
	warn "###CF Download failed: $? $!\n";
}

my $timeend = time;

my $hours = floor (($timeend - $timestart) / (60*60));
my $mins = floor ((($timeend - $timestart) / (60)) - ($hours * 60 * 60));
my $secs = floor (($timeend - $timestart) - ($mins * 60) - ($hours * 60 * 60));

warn "\nDownload took $hours hours, $mins minutes and $secs seconds.\n";

my $date = strftime "%H:%M %d-%m-%Y", localtime;
warn "\nDownload module finished at $date\n---------------------\n";

close (RUN);