#!/usr/bin/perl
use warnings;
use strict;
use FindBin qw($Bin);
use lib "$FindBin::Bin/../source";
use CF::Constants;
use CF::Helpers;
use POSIX qw(strftime);
use Cwd;


# MODULE
# Read in the input files from the run file
my ($files, $runfile, $job_id, $prev_job_id, $cores, $mem, $parameters, $config_ref) = CF::Helpers::load_runfile_params(@ARGV);
my %config = %$config_ref;
my $pipeline = shift(@$parameters);
my @outfns = @$parameters;

# Print run finish status to outfile
my $date = strftime "%H:%M %d-%m-%Y", localtime;
warn "\n###CF Pipeline $pipeline finished at $date\n\n";






# Read in the log files
my @highlights;
push (@highlights, ("=" x 30));
my $outfiles;
foreach my $outfile (@outfns){
	
	$outfiles .= "\n\n".("=" x 60)."\n"."Output file $outfile\n".("=" x 60)."\n";
	
	open (IN,'<',$outfile);
	while(<IN>){
		
		chomp;
		
		# Ignore crap
		if(/^Warning: no access to tty/ || /^Thus no job control in this shell/){
			next;
		}
		
		# Highlight statuses
		if(/^###CF/){
			push (@highlights, substr($_, 6));
		}
		
		# Add cleaned text to outfile string
		$outfiles .= "$_\n";
		
	}
	close (IN);
	$outfiles .= ("\n" x 15);
	push (@highlights, ("=" x 30));
}


# Send e-mail to submitter, if the config demands it
if($config{notifications}{complete} && defined($config{email})){
	
	my $to = $config{email};
	my $subject = "'[CF] $pipeline pipeline compete'";
	
	# Start the e-mail body
my $message_body = "The pipeline $pipeline has completed.

The working directory was ".getcwd()."/
The log files are:
 - ".join("\n - ",@outfns)."

== Highlighted status messages ==
- ".join("\n- ", @highlights)."
\n\n";

# == Full Log File Outputs ==\n";

	open (PIPE , "| mail -s $subject $to") or die "can't open pipe to mail: $!\n";
	print PIPE $message_body;
	# print PIPE $outfiles;	# commented out as notification e-mails were getting huge..
	close PIPE;
	
	sleep(5); # Give mail time to actually send the e-mail before qsub shuts us down
	
	warn "###CF Sent a pipeline e-mail notification to $to\n";

} elsif($config{notifications}{complete} && !defined($config{email})){
	warn "###CF Tried to send run e-mail notification but no e-mail address found in config\n";
}


