#!/usr/bin/perl
use warnings;
use strict;
use Getopt::Long;
use FindBin qw($Bin);
use lib "$FindBin::Bin/../source";
use CF::Constants;
use CF::Helpers;

# Get Options
my $required_cores;
my $required_mem = '';
my $help;
my $result = GetOptions ("cores=i" => \$required_cores, "mem" => \$required_mem, "help" => \$help);

# QSUB SETUP
# --cores i = offered cores. Return number of required cores.
if($required_cores){
	print 1;
	exit;
}
# --mem. Return the required memory allocation.
if($required_mem){
	print '3G';
	exit;
}
# --help. Print help.
if($help){
	print "Help message here";
	exit;
}

# MODULE
# Read in the input files from the run file
my ($files, $runfile, $job_id, $prev_job_id, $cores, $mem, $parameters, $config_ref) = CF::Helpers::load_runfile_params(@ARGV);
my %config = %$config_ref;

# Check that we have a genome defined
if(!defined($config{gtf_path})){
	warn "\n\n### No GTF path found in run file $runfile for job $job_id. Exiting.. ###";
	exit;
}

if(!defined($cores) || $cores <= 0){
	$cores = 1;
}

open (RUN,'>>',$runfile) or die "Can't write to $runfile: $!";

# Separate file names into single end and paired end
my ($se_files, $pe_files) = CF::Helpers::is_paired_end(@$files);

# Go through each single end files and run Tophat
if($se_files && scalar(@$se_files) > 0){
	foreach my $file (@$se_files){
		
		my $output_dir = $file;
		$output_dir =~ s/.gz$//;
		$output_dir =~ s/.fq$//;
		$output_dir =~ s/.fastq$//;
		$output_dir =~ s/_1$//;
		$output_dir =~ s/_2$//;
		
		my $output_fn = $output_dir."/accepted_hits.bam";
		
		if(!system ("tophat -p $cores -g 1 -G ".$config{gtf_path}." -o $output_dir $file")){
			# Tophat worked - print out resulting filenames
			warn "Tophat (SE mode) successfully exited..\n";
			if(-e $output_fn){
				print RUN "$job_id\t$output_fn\n"; 
			} else {
				warn "\nTophat output file $output_fn not found..\n";
			}
		}
	}
}

# Go through the paired end files and run Tophat
if($pe_files && scalar(@$pe_files) > 0){
	foreach my $files_ref (@$pe_files){
		my @files = @$files_ref;
		if(scalar(@files) == 2){
			
			my $output_dir = $file;
			$output_dir =~ s/.gz$//;
			$output_dir =~ s/.fq$//;
			$output_dir =~ s/.fastq$//;
			$output_dir =~ s/_1$//;
			$output_dir =~ s/_2$//;
			
			my $output_fn = $output_dir."/accepted_hits.bam";
			
			if(!system ("tophat -p $cores -g 1 -G ".$config{gtf_path}." -o $output_dir ".$file[0].",".$file[1])){
				# Tophat worked - print out resulting filenames
				warn "Tophat (PE mode) successfully exited..\n";
				if(-e $output_fn){
					print RUN "$job_id\t$output_fn\n";
				} else {
					warn "\nTophat output file $output_fn not found..\n";
				}
			}
		} else {
			warn "\nTophat paired end files had ".scalar(@files)." input files instead of 2..\n";
		}
	}
}


close (RUN);